---
- hosts: all
  gather_facts: false
  #  ignore_errors: true
  tasks:
   - name: check the date
     command: datehj,luuknun
     ignore_errors: yes
   - name: check uptime 
     command: |
        uptime
        date
        nproc
        lsblk 
# this line is to test jenkins ci/cd builod for yml files
